### ISSUE TITLE
Themes dont render correctly

### ISSUE THREAD

**Issue by pantonis** [jonrimmer/ag-grid-themes#1]
Hi,

Themes are not rendered correctly.  Please check the screenshot below

![image](https://cloud.githubusercontent.com/assets/3295086/13567965/0a1d2ec2-e467-11e5-896a-7851806b94f4.png)

Thanks

**Comment by jonrimmer** [comment]
Hi @pantonis, ag-Grid hardcodes the heights of headers and rows, so you will need to change these [in the grid's properties](https://www.ag-grid.com/javascript-grid-properties/index.php) for the theme to look right. The properties to set are `headerHeight` and `rowHeight`. I don't have the exact figures to use right now, but I think they're about 45 for the Clarity theme. If you experiment a bit an you should find a number that looks good.

This theme pack is still a work-in-progress right now (the Material theme isn't even really started). I plan to improve the documentation about this and other issues soon.

**Comment by pantonis** [comment]
ok thanks a lot though. Very good work.
